### PR TITLE
Force python 2 usage

### PR DESCRIPTION
**Pull request by Vedrillan**
> Edit by @phaazon: relates to [this issue](https://github.com/LedgerHQ/lib-ledger-core-node-bindings/issues/17).

### CODE REVIEW

**Comment by phaazon** [comment]
Thanks @Vedrillan. :)

**Comment by Vedrillan** [comment]
:wave: You probably can merge this PR

**Comment by meriadec** [comment]
yeah probably :D

**Comment by gre** [comment]
we're going to revert this because it creates problem for all our devs; It should work regardless of the python version.

in the future, i suggest we move to bash instead of python or pure JS.

**Comment by meriadec** [comment]
Oops

**Comment by phaazon** [comment]
What do you mean it creates problem for all your devs? :cry:

**Comment by gre** [comment]
I was with Khalil and Arnaud and none of us were able to install the lib again. crashes at `python2 command not found` on mac.

**Comment by gre** [comment]
I would suggest we just use a node.js script as it's a node.js library.

**Comment by phaazon** [comment]
I don’t really care about the language used to bundle that. I agree with you about JS, since the whole library is about JS and pretty much everyone has a `npm` install (via `nvm`).

**Comment by meriadec** [comment]
can be easily "fixed" by creating symlink `python2` pointing to correct python 2 binary, but yeah I understand it could be a concern

**Pull request merged**
